# Generated by Django 3.2.4 on 2021-07-01 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AgroApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='creador',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to=settings.AUTH_USER_MODEL),
        ),
    ]
