# Generated by Django 3.2.4 on 2021-06-15 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de tipo de usuario')),
                ('nombreTipoUsuario', models.CharField(max_length=80, verbose_name='Nombre de tipo usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fono', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono usuario')),
                ('direccion', models.CharField(max_length=100, null=True, verbose_name='Dirección usuario')),
                ('descripcionPerfil', models.CharField(max_length=500, null=True, verbose_name='Descripción perfil')),
                ('fotoPerfil', models.ImageField(default='sinfoto.jpg', upload_to='', verbose_name='Foto de perfil')),
                ('cantidadProductos', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de productos')),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Usuario.tipousuario')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
