# Generated by Django 3.2.4 on 2021-06-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_Usuario',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Vendedor', 'Vendedor'), ('Cliente y vendedor', 'Cliente y vendedor')], default='Cliente', max_length=30),
        ),
    ]
