# Generated by Django 3.2.4 on 2021-06-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_remove_usuario_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_Usuario',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Vendedor', 'Vendedor'), ('Cliente y vendedor', 'Cliente y vendedor')], default=22, max_length=30),
            preserve_default=False,
        ),
    ]
