# Generated by Django 3.2.4 on 2021-06-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_Usuario',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Vendedor', 'Vendedor'), ('Cliente y vendedor', 'Cliente y vendedor')], max_length=30, null=True),
        ),
    ]
